"""empty message

Revision ID: e90472f3ee9f
Revises: fa8cf8a7bad7
Create Date: 2020-10-01 17:58:13.126328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90472f3ee9f'
down_revision = 'fa8cf8a7bad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savingsData', sa.Column('salar', sa.Integer(), nullable=True))
    op.drop_column('savingsData', 'salary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savingsData', sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('savingsData', 'salar')
    # ### end Alembic commands ###
