"""empty message

Revision ID: fa8cf8a7bad7
Revises: bd0899cb0d3e
Create Date: 2020-10-01 17:57:06.224090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8cf8a7bad7'
down_revision = 'bd0899cb0d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savingsData', sa.Column('salary', sa.Integer(), nullable=True))
    op.drop_column('savingsData', 'name')
    op.drop_column('savingsData', 'model')
    op.drop_column('savingsData', 'doors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savingsData', sa.Column('doors', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('savingsData', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('savingsData', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('savingsData', 'salary')
    # ### end Alembic commands ###
